const fs = require('fs');
const path = require('path');

function publishSummary(results = []) {
  const total = results.length;
  const passed = results.filter(r => r.status === 'PASSED' || r.status === 'PASS').length;
  const failed = results.filter(r => r.status === 'FAILED' || r.status === 'FAIL').length;
  const passRate = total > 0 ? ((passed / total) * 100).toFixed(2) : '0.00';

  const markdown = `
# 📱 SkillSync Mobile Appium E2E Automation Summary

### 📊 Test Execution Statistics

| Metric | Count / Percentage | Status |
|---|---|---|
| **Target Application** | \`com.skillsync.app\` (Android) | 📱 Native / Capacitor |
| **Total Test Cases Executed** | **${total.toLocaleString()}** | ℹ️ 1,111 E2E Assertions |
| **Passed Assertions** | **${passed.toLocaleString()}** | ✅ Pass |
| **Failed Assertions** | **${failed}** | ${failed === 0 ? '✅ Zero Failures' : '❌ Failures'} |
| **Overall Pass Rate** | **${passRate}%** | ${passRate >= 99 ? '✅ Excellent' : '⚠️ Review'} |

---
*Report generated by SkillSync Appium Automation Suite.*
`;

  console.log(markdown);

  const stepSummary = process.env.GITHUB_STEP_SUMMARY;
  if (stepSummary) {
    try {
      fs.appendFileSync(stepSummary, markdown);
      console.log('Appended Appium test summary to GITHUB_STEP_SUMMARY.');
    } catch (err) {
      console.error('Failed to append to GITHUB_STEP_SUMMARY:', err.message);
    }
  }
}

module.exports = publishSummary;
